# Generated by Django 4.1.5 on 2023-03-26 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_managment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
