# Generated by Django 4.1.5 on 2023-04-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='images',
            new_name='image',
        ),
    ]
