# Generated by Django 4.1.5 on 2023-04-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_rename_images_disease_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='tags',
        ),
    ]
